### ISSUE TITLE
为啥运行部不起来呢，运行报错

### ISSUE THREAD

**Issue by skytosky** [chin-ray/Famous_and_Ancient_Trees#2]
Users/wangtonglong/Desktop/Project/Famous_and_Ancient_Trees/server/routes/functions.js:59
        connection.query(sql, params, function (err, result) {
                   ^

TypeError: Cannot read properties of undefined (reading 'query')
    at query (/Users/wangtonglong/Desktop/Project/Famous_and_Ancient_Trees/server/routes/functions.js:59:20)
    at /Users/wangtonglong/Desktop/Project/Famous_and_Ancient_Trees/server/routes/user/config.js:31:17
    at Handshake.onConnect (/Users/wangtonglong/Desktop/Project/Famous_and_Ancient_Trees/server/node_modules/mysql/lib/Pool.js:58:9)
    at Handshake.<anony

**Comment by skytosky** [comment]
知道原因了 缺少太多东西，基本的数据库没有，数据库database 能提供一下吗
